
package Vista;

import Controlador.EmpleadoControlador;
import Modelo.Empleado;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import javax.swing.JTextField;

/**
 *
 * @author Edith Cruz
 */
public class VistaEmpleado extends javax.swing.JPanel {

    private final EmpleadoControlador empleadoControlador;
    private Integer idEmpleadoSeleccionado = null;

    /**
     * Creates new form VsitaEmpleados
     */
    public VistaEmpleado() {
        initComponents();
        this.empleadoControlador = new EmpleadoControlador();
        selectorfechaContratacion.setDate(new Date());
        ((JTextField) selectorfechaContratacion.getDateEditor().getUiComponent()).setEditable(false);
        cargarDatosTabla();
    }

    private void cargarDatosTabla() {
        List<Empleado> empleados = empleadoControlador.obtenerTodosEmpleados();
        if (empleados != null) {
            DefaultTableModel model = (DefaultTableModel) tablaEmpleado.getModel();
            model.setRowCount(0);
            for (Empleado emp : empleados) {
                Object[] row = {
                    emp.getIdEmpleado(),
                    emp.getPrimerNombre(),
                    emp.getSegundoNombre(),
                    emp.getPrimerApellido(),
                    emp.getSegundoApellido(),
                    emp.getCelular(),
                    emp.getCargo(),
                    emp.getFechaContratacion()
                };
                model.addRow(row);
            }
        }
    }

    private void limpiar() {
        textprimerNombre.setText("");
        textsegundoNombre.setText("");
        textprimerApellido.setText("");
        textsegundoApellido.setText("");
        textcelular.setText("");
        textBuscar.setText("");
        idEmpleadoSeleccionado = null;
        selectorfechaContratacion.setDate(new Date());
        btnEliminar.setEnabled(true);
        btnGuardar.setEnabled(true);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textprimerNombre = new javax.swing.JTextField();
        textsegundoNombre = new javax.swing.JTextField();
        textprimerApellido = new javax.swing.JTextField();
        textsegundoApellido = new javax.swing.JTextField();
        textcelular = new javax.swing.JTextField();
        Combocargo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        textBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleado = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        selectorfechaContratacion = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PrimerNombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, -1, -1));

        jLabel2.setText("SegundoNombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 18, -1, -1));

        jLabel3.setText("PrimerApellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 18, -1, -1));

        jLabel4.setText("Celular");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 18, -1, -1));

        jLabel5.setText("SegundoApellido");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 18, -1, -1));

        jLabel6.setText("Cargo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 18, -1, -1));
        jPanel1.add(textprimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 93, -1));

        textsegundoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textsegundoNombreActionPerformed(evt);
            }
        });
        jPanel1.add(textsegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 40, 104, -1));

        textprimerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textprimerApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(textprimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 40, 101, -1));
        jPanel1.add(textsegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 40, 98, -1));

        textcelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcelularActionPerformed(evt);
            }
        });
        jPanel1.add(textcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 40, 91, -1));

        Combocargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supervisor", "Gerente", "Caja", " " }));
        jPanel1.add(Combocargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 40, 79, -1));

        jLabel7.setText("Fechacontratacion");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 18, -1, -1));

        textBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textBuscarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textBuscarKeyTyped(evt);
            }
        });
        jPanel1.add(textBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 330, -1));

        tablaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id_Empleado", " Nombre 1", " Nombre 2", " Apellido 1", " Apellido 2", "Celular", "Cargo", "Fecha Contratacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEmpleado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 134, 770, 311));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccionBotonGuardar(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 93, 96, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccionBotonLimpiar(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 93, 106, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonEliminar(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 93, 102, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcciónBotonActualizar(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 93, 91, -1));
        jPanel1.add(selectorfechaContratacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 40, 128, -1));

        jLabel8.setText("Buscar");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 68, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textsegundoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textsegundoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textsegundoNombreActionPerformed

    private void textprimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textprimerApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textprimerApellidoActionPerformed

    private void textcelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcelularActionPerformed

    private void AccionBotonGuardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccionBotonGuardar
Date fecha = this.selectorfechaContratacion.getDate();
        java.sql.Date fechaContratacion = new java.sql.Date(fecha.getTime());
        String PrimerNombre = textprimerNombre.getText();
        String SegundoNombre = textsegundoNombre.getText();
        String PrimerApellido = textprimerApellido.getText();
        String SegundoApellido = textsegundoApellido.getText();
        String Celular = textcelular.getText();
        String Cargo = (String) Combocargo.getSelectedItem();

        if (!PrimerNombre.isEmpty() && !PrimerApellido.isEmpty() && !Celular.isEmpty() && !Cargo.isEmpty()) {
            try {
                empleadoControlador.crearEmpleado(PrimerNombre, SegundoNombre, PrimerApellido, SegundoApellido, Celular, Cargo, fechaContratacion);
                limpiar();
                cargarDatosTabla();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Llene los campos requeridos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_AccionBotonGuardar

    private void accionBotonEliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonEliminar
      int filaSeleccionada = tablaEmpleado.getSelectedRow();
        if (filaSeleccionada != -1) {
            int idEmpleado = (int) tablaEmpleado.getValueAt(filaSeleccionada, 0);
            empleadoControlador.eliminarEmpleado(idEmpleado);
            cargarDatosTabla();
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar. ", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_accionBotonEliminar

    private void AcciónBotonActualizar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcciónBotonActualizar
       String primerNombre = textprimerNombre.getText();
        String segundoNombre = textsegundoNombre.getText();
        String primerApellido = textprimerApellido.getText();
        String segundoApellido = textsegundoApellido.getText();
        String celular = textcelular.getText();
        String cargo = (String) Combocargo.getSelectedItem();
        Date fecha = this.selectorfechaContratacion.getDate();
        java.sql.Date fechaContratacion = new java.sql.Date(fecha.getTime());

        if (idEmpleadoSeleccionado != null && !primerNombre.isEmpty() && !primerApellido.isEmpty() && !celular.isEmpty()) {
            try {
                empleadoControlador.actualizarEmpleado(idEmpleadoSeleccionado, primerNombre, segundoNombre, primerApellido, segundoApellido,
                        celular, cargo, fechaContratacion);
                cargarDatosTabla();
                limpiar();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
        }
    }//GEN-LAST:event_AcciónBotonActualizar

    private void textBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBuscarKeyPressed
      String textoBusqueda = textBuscar.getText().trim().toLowerCase();
        List<Empleado> empleados = empleadoControlador.obtenerTodosEmpleados();

        DefaultTableModel modelo = (DefaultTableModel) tablaEmpleado.getModel();
        modelo.setRowCount(0);

        if (empleados != null) {
            for (Empleado emp : empleados) {
                if (textoBusqueda.isEmpty()
                        || emp.getPrimerNombre().toLowerCase().contains(textoBusqueda)
                        || (emp.getSegundoNombre() != null && emp.getSegundoNombre().toLowerCase().contains(textoBusqueda))
                        || emp.getPrimerApellido().toLowerCase().contains(textoBusqueda)
                        || (emp.getSegundoApellido() != null && emp.getSegundoApellido().toLowerCase().contains(textoBusqueda))
                        || emp.getCelular().toLowerCase().contains(textoBusqueda)
                        || emp.getCargo().toLowerCase().contains(textoBusqueda)) {

                }

                Object[] fila = {
                    emp.getIdEmpleado(),
                    emp.getPrimerNombre(),
                    emp.getSegundoNombre(),
                    emp.getPrimerApellido(),
                    emp.getSegundoApellido(),
                    emp.getCelular(),
                    emp.getCargo(),
                    emp.getFechaContratacion()
                };
                modelo.addRow(fila);

            }
        }
    }//GEN-LAST:event_textBuscarKeyPressed

    private void AccionBotonLimpiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccionBotonLimpiar
       textprimerNombre.setText("");

        textsegundoNombre.setText("");

        textprimerApellido.setText("");

        textsegundoApellido.setText("");

        textcelular.setText("");

        Combocargo.getSelectedItem();

        selectorfechaContratacion.getDate();

        btnEliminar.setEnabled(true);

        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_AccionBotonLimpiar

    private void tablaEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEmpleadoMouseClicked
       if (evt.getClickCount() == 2) {
            int filaSeleccionada = tablaEmpleado.getSelectedRow();
            if (filaSeleccionada != -1) {
                idEmpleadoSeleccionado = (int) tablaEmpleado.getValueAt(filaSeleccionada, 0);
                String primerNombre = (String) tablaEmpleado.getValueAt(filaSeleccionada, 1);
                String segundoNombre = (String) tablaEmpleado.getValueAt(filaSeleccionada, 2);
                String primerApellido = (String) tablaEmpleado.getValueAt(filaSeleccionada, 3);
                String segundoApellido = (String) tablaEmpleado.getValueAt(filaSeleccionada, 4);
                String celular = (String) tablaEmpleado.getValueAt(filaSeleccionada, 5);
                String cargo = (String) tablaEmpleado.getValueAt(filaSeleccionada, 6);
                Date fecha = (Date) tablaEmpleado.getValueAt(filaSeleccionada, 7);

                textprimerNombre.setText(primerNombre);
                textsegundoNombre.setText(segundoNombre != null ? segundoNombre : "");
                textprimerApellido.setText(primerApellido);
                textsegundoApellido.setText(segundoApellido != null ? segundoApellido : "");
                textcelular.setText(celular);
                Combocargo.setSelectedItem(cargo != null ? cargo : "Seleccionar");

                selectorfechaContratacion.setDate(fecha);

                btnEliminar.setEnabled(false);
                btnGuardar.setEnabled(false);

            }
        } 
    }//GEN-LAST:event_tablaEmpleadoMouseClicked

    private void textBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBuscarKeyTyped
        String textoBusqueda = textBuscar.getText().trim().toLowerCase();
        List<Empleado> empleados = empleadoControlador.obtenerTodosEmpleados();

        DefaultTableModel modelo = (DefaultTableModel) tablaEmpleado.getModel();
        modelo.setRowCount(0);

        if (empleados != null) {
            for (Empleado emp : empleados) {
                if (textoBusqueda.isEmpty()
                        || emp.getPrimerNombre().toLowerCase().contains(textoBusqueda)
                        || (emp.getSegundoNombre() != null && emp.getSegundoNombre().toLowerCase().contains(textoBusqueda))
                        || emp.getPrimerApellido().toLowerCase().contains(textoBusqueda)
                        || (emp.getSegundoApellido() != null && emp.getSegundoApellido().toLowerCase().contains(textoBusqueda))
                        || emp.getCelular().toLowerCase().contains(textoBusqueda)
                        || emp.getCargo().toLowerCase().contains(textoBusqueda)) {
                    Object[] fila = {
                    emp.getIdEmpleado(),
                    emp.getPrimerNombre(),
                    emp.getSegundoNombre(),
                    emp.getPrimerApellido(),
                    emp.getSegundoApellido(),
                    emp.getCelular(),
                    emp.getCargo(),
                    emp.getFechaContratacion()
                };
                modelo.addRow(fila);

            }
        }
    }                                    
    }//GEN-LAST:event_textBuscarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combocargo;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser selectorfechaContratacion;
    private javax.swing.JTable tablaEmpleado;
    private javax.swing.JTextField textBuscar;
    private javax.swing.JTextField textcelular;
    private javax.swing.JTextField textprimerApellido;
    private javax.swing.JTextField textprimerNombre;
    private javax.swing.JTextField textsegundoApellido;
    private javax.swing.JTextField textsegundoNombre;
    // End of variables declaration//GEN-END:variables
}
