/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ClienteControlador;
import Modelo.Cliente;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edith Cruz
 */
public class VistaClientes extends javax.swing.JPanel {

    private final ClienteControlador clienteControlador;
    private Integer id_ClienteSeleccionada = null;

    public VistaClientes() {
        initComponents();
        this.clienteControlador = new ClienteControlador();
        cargarDatosTabla();
    }

    public void cargarDatosTabla() {

        List<Cliente> cliente = clienteControlador.obtenerTodosClientes();

        if (cliente != null) {
            DefaultTableModel model = (DefaultTableModel) tablaCliente.getModel();
            model.setRowCount(0);

            for (Cliente cli : cliente) {
                Object[] row = {
                    cli.getIdCliente(),
                    cli.getPrimerNombre(),
                    cli.getSegundoNombre(),
                    cli.getPrimerApellido(),
                    cli.getSegundoApellido(),
                    cli.getCelular(),
                    cli.getDireccion(),
                    cli.getCedula()
                };
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textprimerNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textsegundoNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textprimerApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textsegundoApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textcelular = new javax.swing.JTextField();
        textdireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textcedula = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        textBuscar = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Primer Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 12, -1, -1));
        jPanel1.add(textprimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 143, -1));

        jLabel2.setText("Segundo Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 12, -1, -1));
        jPanel1.add(textsegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 34, 138, -1));

        jLabel3.setText("Primer Apellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 12, -1, -1));
        jPanel1.add(textprimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 34, 144, -1));

        jLabel4.setText("Segundo Nombre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 12, -1, -1));

        textsegundoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textsegundoApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(textsegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 34, 136, -1));

        jLabel5.setText("Celular");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 12, -1, -1));

        textcelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcelularActionPerformed(evt);
            }
        });
        jPanel1.add(textcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 34, 148, -1));

        textdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textdireccionActionPerformed(evt);
            }
        });
        jPanel1.add(textdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 143, -1));

        jLabel6.setText("Direccion");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 62, -1, -1));

        jLabel7.setText("Celula");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 70, -1, -1));
        jPanel1.add(textcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 93, 138, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonGuardar(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 133, 120, -1));

        textBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textBuscarKeyTyped(evt);
            }
        });
        jPanel1.add(textBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 93, 330, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonLimpiar(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 133, 120, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonEliminar(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 133, 120, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonActualizar(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 133, 120, -1));

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Cliente", "Nombre1", "Nombre2", "Apellido1", "Apellido2", "Celular", "Direccion", "Celula"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCliente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 166, 776, 297));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textcelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcelularActionPerformed

    private void textsegundoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textsegundoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textsegundoApellidoActionPerformed

    private void textdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textdireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textdireccionActionPerformed

    private void accionBotonLimpiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonLimpiar
        textprimerNombre.setText("");
        textsegundoNombre.setText("");
        textprimerApellido.setText("");
        textsegundoApellido.setText("");
        textcelular.setText("");
        textdireccion.setText("");
        textcedula.setText("");
        btnEliminar.setEnabled(true);
        btnGuardar.setEnabled(true);
        cargarDatosTabla(); // Reload
    }//GEN-LAST:event_accionBotonLimpiar

    private void accionBotonGuardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonGuardar
        String primerNombre = textprimerNombre.getText();
        String segundoNombre = textsegundoNombre.getText();
        String primerApellido = textprimerApellido.getText();
        String segundoApellido = textsegundoApellido.getText();
        String Celular = textcelular.getText();
        String Direccion = textdireccion.getText();
        String Cedula = textcedula.getText();

        if (!primerNombre.isEmpty() && !segundoNombre.isEmpty() && !primerApellido.isEmpty() && !segundoApellido.isEmpty() && !Celular.isEmpty()
                && !Direccion.isEmpty() && !Cedula.isEmpty()) {
            clienteControlador.crearCliente(primerNombre, segundoNombre, primerApellido, segundoApellido, Celular, Direccion, Cedula);
            cargarDatosTabla();

            textprimerNombre.setText("");
            textsegundoNombre.setText("");
            textprimerApellido.setText("");
            textsegundoApellido.setText("");
            textcelular.setText("");
            textdireccion.setText("");
            textcedula.setText("");

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llene los campos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accionBotonGuardar

    private void accionBotonActualizar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonActualizar
       String primerNombre = textprimerNombre.getText();
        String segundoNombre = textsegundoNombre.getText();
        String primerApellido = textprimerApellido.getText();
        String segundoApellido = textsegundoApellido.getText();
        String Celular = textcelular.getText();
        String Direccion = textdireccion.getText();
        String Cedula = textcedula.getText();

        if (!primerNombre.isEmpty() && !segundoNombre.isEmpty() && !primerApellido.isEmpty() && !segundoApellido.isEmpty() && !Celular.isEmpty()
                && !Direccion.isEmpty() && !Cedula.isEmpty()) {
            clienteControlador.crearCliente(primerNombre, segundoNombre, primerApellido, segundoApellido, Celular, Direccion, Cedula);
            cargarDatosTabla();

            textprimerNombre.setText(primerNombre);
            textsegundoNombre.setText(segundoNombre);
            textprimerApellido.setText(primerApellido);
            textsegundoApellido.setText(segundoApellido);
            textcelular.setText(Celular);
            textdireccion.setText(Direccion);
            textcedula.setText(Cedula);
            id_ClienteSeleccionada = null;

            btnEliminar.setEnabled(true);
            btnGuardar.setEnabled(true);

        } else {

            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llene los campos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_accionBotonActualizar

    private void accionBotonEliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonEliminar
        int filaSeleccionada = tablaCliente.getSelectedRow();
        if (filaSeleccionada != -1) {
            int id_Cliente = (int) tablaCliente.getValueAt(filaSeleccionada, 0);
            clienteControlador.eliminarCliente(id_Cliente);
            cargarDatosTabla();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar.", "error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accionBotonEliminar

    private void textBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBuscarKeyTyped
       String textoBusqueda = textBuscar.getText().trim().toLowerCase();
        List<Cliente> cliente = clienteControlador.obtenerTodosClientes();

        DefaultTableModel modelo = (DefaultTableModel) tablaCliente.getModel();
        modelo.setRowCount(0);

        if (cliente != null) {
            for (Cliente cli : cliente) {
                if (textoBusqueda.isEmpty()
                        || cli.getPrimerNombre().toLowerCase().contains(textoBusqueda)
                        || cli.getSegundoNombre().toLowerCase().contains(textoBusqueda)
                        || cli.getPrimerApellido().toLowerCase().contains(textoBusqueda)
                        || cli.getSegundoApellido().toLowerCase().contains(textoBusqueda)
                        || cli.getCelular().toLowerCase().contains(textoBusqueda)
                        || cli.getDireccion().toLowerCase().contains(textoBusqueda)
                        || cli.getCedula().toLowerCase().contains(textoBusqueda)) {

                    Object[] fila = {
                        cli.getIdCliente(),
                        cli.getPrimerNombre(),
                        cli.getSegundoNombre(),
                        cli.getPrimerApellido(),
                        cli.getSegundoApellido(),
                        cli.getCelular(),
                        cli.getDireccion(),
                        cli.getCedula()
                    };
                    modelo.addRow(fila);
                }
            }
        }

    }//GEN-LAST:event_textBuscarKeyTyped

    private void tablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClienteMouseClicked
         if (evt.getClickCount() == 2) {

            int filaSeleccionada = tablaCliente.getSelectedRow();

            if (filaSeleccionada != -1) {

                id_ClienteSeleccionada = (int) tablaCliente.getValueAt(filaSeleccionada, 0);
                String primerNombre = (String) tablaCliente.getValueAt(filaSeleccionada, 1);
                String segundoNombre = (String) tablaCliente.getValueAt(filaSeleccionada, 2);
                String primerApellido = (String) tablaCliente.getValueAt(filaSeleccionada, 3);
                String segundoApellido = (String) tablaCliente.getValueAt(filaSeleccionada, 4);
                String Celular = (String) tablaCliente.getValueAt(filaSeleccionada, 5);
                String Direccion = (String) tablaCliente.getValueAt(filaSeleccionada, 6);
                String Cedula = (String) tablaCliente.getValueAt(filaSeleccionada, 7);
                
                textprimerNombre.setText(primerNombre);
                textsegundoNombre.setText(segundoNombre);
                textprimerApellido.setText(primerApellido);
                textsegundoApellido.setText(segundoApellido);
                textcelular.setText(Celular);
                textdireccion.setText(Direccion);
                textcedula.setText(Cedula);

                btnEliminar.setEnabled(false);
                btnGuardar.setEnabled(false);

            }
        }
    }//GEN-LAST:event_tablaClienteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTextField textBuscar;
    private javax.swing.JTextField textcedula;
    private javax.swing.JTextField textcelular;
    private javax.swing.JTextField textdireccion;
    private javax.swing.JTextField textprimerApellido;
    private javax.swing.JTextField textprimerNombre;
    private javax.swing.JTextField textsegundoApellido;
    private javax.swing.JTextField textsegundoNombre;
    // End of variables declaration//GEN-END:variables
}
