/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.UsuarioControlador;
import Modelo.Usuario;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Edith Cruz
 */
public class VistaUsuario extends javax.swing.JPanel {

     private final UsuarioControlador usuarioControlador;
     private Integer idUsuarioSeleccionado = null ;
      
    /**
     * Creates new form VistaUsuario
     */
    public VistaUsuario() {
        initComponents();
        this.usuarioControlador = new UsuarioControlador();
        cargarDatosTabla();
    }

 private void cargarDatosTabla() {
        List<Usuario> usuario = usuarioControlador.obtenerTodosUsuarios();
        if (usuario != null) {
            DefaultTableModel model = (DefaultTableModel) tablaUsuario.getModel();
            model.setRowCount(0);
            for (Usuario usua : usuario) {
                Object[] row = {
                    usua.getIdUsuario(),
                    usua.getUsuario(),
                    usua.getContrasena()
                };
                model.addRow(row);
            }
        }
    }

    private void limpiar() {
        textusuario.setText("");
        textcontraseña = new javax.swing.JPasswordField();
        btnEliminar.setEnabled(true);
        btnGuardar.setEnabled(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textusuario = new javax.swing.JTextField();
        textcontraseña = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuario = new javax.swing.JTable();
        textBuscar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 6, -1, -1));

        jLabel2.setText("Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 6, -1, -1));

        textusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textusuarioActionPerformed(evt);
            }
        });
        jPanel1.add(textusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 160, -1));
        jPanel1.add(textcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 34, 160, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
                accionBotonGuardar(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 81, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
                accionBotonLimpiar(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 91, 81, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonEliminar(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 231, 82, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonActualizar(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 298, -1, -1));

        tablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Usuario", "Usuario", "Contraseña"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 74, 652, 356));

        textBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textBuscarKeyTyped(evt);
            }
        });
        jPanel1.add(textBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 34, 334, -1));

        jLabel3.setText("Buscar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 6, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textusuarioActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void accionBotonGuardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonGuardar
      String Usuario = textusuario.getText();
        String Contraseña = textcontraseña.getText();

        if (Usuario != null && !Contraseña.isEmpty()) {
            try {
                usuarioControlador.crearUsuario(Usuario, Contraseña);
                cargarDatosTabla();
                limpiar();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
        }

    }//GEN-LAST:event_accionBotonGuardar

    private void accionBotonEliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonEliminar
            int filaSeleccionada = tablaUsuario.getSelectedRow();
        if (filaSeleccionada != -1) {
            int idUsuario = (int) tablaUsuario.getValueAt(filaSeleccionada, 0);
            usuarioControlador.eliminarUsuario(idUsuario);
            cargarDatosTabla(); // corregido
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar. ", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_accionBotonEliminar

    private void accionBotonActualizar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonActualizar
       String Usuario = textusuario.getText();
        String Contraseña = textcontraseña.getText();

        if (Usuario != null && !Contraseña.isEmpty()) {
            usuarioControlador.actualizarUsuario(0, Usuario, Contraseña);
            textusuario.setText("");
            textcontraseña = new javax.swing.JPasswordField();

            btnEliminar.setEnabled(true);
            btnGuardar.setEnabled(true);
        }

    }//GEN-LAST:event_accionBotonActualizar

    private void tablaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuarioMouseClicked
        if (evt.getClickCount() == 2) {

            int filaSeleccionada = tablaUsuario.getSelectedRow();

            if (filaSeleccionada != -1) {

                idUsuarioSeleccionado = (int) tablaUsuario.getValueAt(filaSeleccionada, 0);
                String Usuario = (String) tablaUsuario.getValueAt(filaSeleccionada, 1);
                String contraseña = (String) tablaUsuario.getValueAt(filaSeleccionada, 2);

                textusuario.setText(Usuario);
                textcontraseña = new javax.swing.JPasswordField(contraseña);

                btnEliminar.setEnabled(false);
                btnGuardar.setEnabled(false);

            }
        }

    }//GEN-LAST:event_tablaUsuarioMouseClicked

    private void textBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBuscarKeyTyped
         String textoBusqueda = textBuscar.getText().trim().toLowerCase();
        List<Usuario> usuario = usuarioControlador.obtenerTodosUsuarios();

        DefaultTableModel modelo = (DefaultTableModel) tablaUsuario.getModel();
        modelo.setRowCount(0);

        if (usuario != null) {
            for (Usuario usua : usuario) {
                if (textoBusqueda.isEmpty()
                        || usua.getUsuario().toLowerCase().contains(textoBusqueda)
                        || usua.getContrasena().toLowerCase().contains(textoBusqueda)) {

                    Object[] row = {
                        usua.getIdUsuario(),
                        usua.getUsuario(),
                        usua.getContrasena()
                    };
                    modelo.addRow(row);
                }
            }
        }

    }//GEN-LAST:event_textBuscarKeyTyped

    private void accionBotonLimpiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonLimpiar
     limpiar();
    }//GEN-LAST:event_accionBotonLimpiar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsuario;
    private javax.swing.JTextField textBuscar;
    private javax.swing.JTextField textcontraseña;
    private javax.swing.JTextField textusuario;
    // End of variables declaration//GEN-END:variables
}
